export enum TokenType {
  BEARER = 'Bearer',
  REFRESH = 'Refresh',
}

export enum ConfigVars {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_ACCESS_EXPIRES_IN = 'JWT_ACCESS_EXPIRES_IN',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
  MONGO_URI = 'MONGO_URI',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  FRONTEND_URL = 'FRONTEND_URL',
}
